plugins {
    id 'java'
}

group = 'org.dodo'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.seleniumhq.selenium:selenium-java:4.45.0")
    testImplementation("io.github.bonigarcia:webdrivermanager:6.3.4")
    testImplementation("io.cucumber:cucumber-java:7.34.4")
    testImplementation("io.cucumber:cucumber-junit-platform-engine:7.34.4")
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.junit.platform:junit-platform-suite'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

configurations {
    cucumberRuntime{
        extendsFrom(testImplementation)
    }
}

def tags = (findProperty('tags') == null) ? 'not @exclude' : findProperty('tags') + ' and not @exclude'

tasks.register('cucumber', JavaExec) {
    description = "Running Cucumber Test"
    dependsOn assemble, compileTestJava
    mainClass = "io.cucumber.core.cli.Main"
    classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output

    args = [
            '--plugin', 'pretty',
            '--plugin', 'html:build/reports/cucumber/cucumber.html',
            '--plugin', 'json:build/reports/cucumber/cucumber.json',
            '--glue', 'stepdef',
            '--tags', "${tags}",
            'src/test/resources'
    ]
}